exit with error count

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -74,5 +74,9 @@ runs:
     run: |
       ./apic --mode governance compliance:validate  --insecure-skip-tls-verify --server ${{ inputs.api-host }} --org ${{ inputs.provider-org }} ${{ inputs.api-spec }} --format json > compliance.json
       jq -cr '.errors[] | if .severity == "error" then "::" + .severity else "::warning" end + " file=${{ inputs.api-spec }},line=\(.start_line)::title=\(.severity): \(.ruleset_name) \(.rule_name)::\(.message)"' compliance.json
+      ERROR_COUNT=$(jq '[.errors[] | select(.severity == "error")] | length' compliance.json)
+      echo "Found $ERROR_COUNT error(s)"
+      exit $ERROR_COUNT
+      
 
       
